import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mtwenty.one Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://mtwenty.one">mtwenty.one!</a>
        </h1>

        <p className={styles.description}>
          Get started by by selecting your{' '}
          <code className={styles.code}>/Path</code>
        </p>

        <div className={styles.grid}>
          <a href="https://mtwenty.one/nextcloud" target="_blank" className={styles.card}>
            <h2>Cloud Storage &rarr;</h2>
            <p>Start storing all your Data on the Mtwenty.one Cloud Service</p>
          </a>

          <a href="https://mtwenty.one/home" className={styles.card}>
            <h2>Official Website &rarr;</h2>
            <p>Learn more about Mtwenty.one on our interactive website</p>
          </a>

          <a
            href="https://test.mtwenty.one"
            className={styles.card}
          >
            <h2>Crypto Project by Mtwenty.one &rarr;</h2>
            <p>Our Pancakeswap fork testnet environment for the BSC network</p>
          </a>

          <a
            href="https://discord.com"
            className={styles.card}
          >
            <h2>Discord &rarr;</h2>
            <p>
              Come and join our official Discord Server. We always miss kyle!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://mtwenty.one"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logo.png" alt="MtwentyOne Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
